import {StyleSheet} from 'react-native';

export const colors = {
  background: '#eef4fa',
  border: '#d7e1ec',
  card: '#ffffff',
  danger: '#b42318',
  dangerSoft: '#fee4e2',
  header: '#0f1f3d',
  muted: '#64748b',
  primary: '#2563eb',
  primaryDark: '#1d4ed8',
  primarySoft: '#dbeafe',
  steel: '#486581',
  steelSoft: '#edf2f7',
  success: '#0f766e',
  successSoft: '#ccfbf1',
  surface: '#f8fafc',
  text: '#172033',
  warning: '#b45309',
  warningSoft: '#fef3c7',
};

export const sharedStyles = StyleSheet.create({
  button: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 8,
    elevation: 1,
    minHeight: 42,
    paddingHorizontal: 14,
    paddingVertical: 11,
    shadowColor: '#0f1f3d',
    shadowOffset: {height: 1, width: 0},
    shadowOpacity: 0.12,
    shadowRadius: 2,
  },
  buttonDanger: {
    backgroundColor: colors.danger,
  },
  buttonGhost: {
    backgroundColor: colors.steelSoft,
    elevation: 0,
    shadowOpacity: 0,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  buttonTextDark: {
    color: colors.header,
    fontSize: 14,
    fontWeight: '700',
  },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    elevation: 2,
    padding: 16,
    shadowColor: '#10203b',
    shadowOffset: {height: 2, width: 0},
    shadowOpacity: 0.07,
    shadowRadius: 6,
  },
  container: {
    backgroundColor: colors.background,
    flex: 1,
  },
  errorBox: {
    backgroundColor: colors.dangerSoft,
    borderColor: '#fda29b',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  errorText: {
    color: colors.danger,
    fontSize: 14,
    lineHeight: 20,
  },
  fieldLabel: {
    color: colors.header,
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 6,
  },
  header: {
    backgroundColor: colors.header,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    elevation: 4,
    paddingBottom: 22,
    paddingHorizontal: 20,
    paddingTop: 28,
    shadowColor: '#0b1220',
    shadowOffset: {height: 3, width: 0},
    shadowOpacity: 0.18,
    shadowRadius: 8,
  },
  headerEyebrow: {
    color: '#bfdbfe',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  headerTitle: {
    color: '#ffffff',
    fontSize: 26,
    fontWeight: '800',
    marginTop: 4,
  },
  input: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    color: colors.text,
    fontSize: 15,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  muted: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  screenBody: {
    gap: 14,
    padding: 16,
  },
});
