import {StyleSheet} from 'react-native';

export const colors = {
  background: '#EEF2F7',
  border: '#CBD5E1',
  card: '#FFFFFF',
  danger: '#DC2626',
  dangerSoft: '#FEE2E2',
  header: '#0F172A',
  muted: '#64748B',
  primary: '#2563EB',
  primaryDark: '#1E3A8A',
  primarySoft: '#DBEAFE',
  steel: '#334155',
  steelSoft: '#E2E8F0',
  success: '#16A34A',
  successSoft: '#DCFCE7',
  surface: '#F8FAFC',
  text: '#111827',
  warning: '#F59E0B',
  warningSoft: '#FEF3C7',
};

export const sharedStyles = StyleSheet.create({
  button: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 8,
    elevation: 3,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: colors.primaryDark,
    shadowOffset: {height: 2, width: 0},
    shadowOpacity: 0.18,
    shadowRadius: 4,
  },
  buttonDanger: {
    backgroundColor: colors.danger,
  },
  buttonGhost: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    elevation: 0,
    shadowOpacity: 0,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  buttonTextDark: {
    color: colors.header,
    fontSize: 14,
    fontWeight: '700',
  },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    elevation: 3,
    padding: 17,
    shadowColor: colors.header,
    shadowOffset: {height: 3, width: 0},
    shadowOpacity: 0.09,
    shadowRadius: 8,
  },
  container: {
    backgroundColor: colors.background,
    flex: 1,
  },
  errorBox: {
    backgroundColor: colors.dangerSoft,
    borderColor: '#FCA5A5',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  errorText: {
    color: colors.danger,
    fontSize: 14,
    lineHeight: 20,
  },
  fieldLabel: {
    color: colors.header,
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 6,
  },
  header: {
    backgroundColor: colors.header,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    elevation: 7,
    paddingBottom: 24,
    paddingHorizontal: 20,
    paddingTop: 30,
    shadowColor: colors.header,
    shadowOffset: {height: 5, width: 0},
    shadowOpacity: 0.24,
    shadowRadius: 10,
  },
  headerEyebrow: {
    color: '#bfdbfe',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  headerTitle: {
    color: '#ffffff',
    fontSize: 27,
    fontWeight: '900',
    lineHeight: 33,
    marginTop: 8,
  },
  input: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    color: colors.text,
    fontSize: 15,
    minHeight: 44,
    paddingHorizontal: 13,
    paddingVertical: 11,
  },
  muted: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  screenBody: {
    gap: 16,
    padding: 16,
    paddingBottom: 28,
  },
});
