// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RangeTech.ServiceApp.Api.Infrastructure.Persistence;

#nullable disable

namespace RangeTech.ServiceApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515075023_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.ServicePart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ServiceParts");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.ServiceReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ServiceTicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceTicketId");

                    b.ToTable("ServiceReports");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.ServiceReportPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("int");

                    b.Property<Guid>("ServicePartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceReportId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServicePartId");

                    b.HasIndex("ServiceReportId", "ServicePartId");

                    b.ToTable("ServiceReportParts");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.ServiceTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DeviceId");

                    b.ToTable("ServiceTickets");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.TaskType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("TaskTypes");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.WorkTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ScheduledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("TaskTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TaskTypeId");

                    b.ToTable("WorkTasks");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.Device", b =>
                {
                    b.HasOne("RangeTech.ServiceApp.Api.Domain.Entities.Client", "Client")
                        .WithMany("Devices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.ServiceReport", b =>
                {
                    b.HasOne("RangeTech.ServiceApp.Api.Domain.Entities.Employee", "Employee")
                        .WithMany("ServiceReports")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RangeTech.ServiceApp.Api.Domain.Entities.ServiceTicket", "ServiceTicket")
                        .WithMany("ServiceReports")
                        .HasForeignKey("ServiceTicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ServiceTicket");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.ServiceReportPart", b =>
                {
                    b.HasOne("RangeTech.ServiceApp.Api.Domain.Entities.ServicePart", "ServicePart")
                        .WithMany("ServiceReportParts")
                        .HasForeignKey("ServicePartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RangeTech.ServiceApp.Api.Domain.Entities.ServiceReport", "ServiceReport")
                        .WithMany("ServiceReportParts")
                        .HasForeignKey("ServiceReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicePart");

                    b.Navigation("ServiceReport");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.ServiceTicket", b =>
                {
                    b.HasOne("RangeTech.ServiceApp.Api.Domain.Entities.Client", "Client")
                        .WithMany("ServiceTickets")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RangeTech.ServiceApp.Api.Domain.Entities.Device", "Device")
                        .WithMany("ServiceTickets")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.WorkTask", b =>
                {
                    b.HasOne("RangeTech.ServiceApp.Api.Domain.Entities.Device", "Device")
                        .WithMany("WorkTasks")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RangeTech.ServiceApp.Api.Domain.Entities.Employee", "Employee")
                        .WithMany("WorkTasks")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RangeTech.ServiceApp.Api.Domain.Entities.TaskType", "TaskType")
                        .WithMany("WorkTasks")
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Employee");

                    b.Navigation("TaskType");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.Client", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("ServiceTickets");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.Device", b =>
                {
                    b.Navigation("ServiceTickets");

                    b.Navigation("WorkTasks");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.Employee", b =>
                {
                    b.Navigation("ServiceReports");

                    b.Navigation("WorkTasks");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.ServicePart", b =>
                {
                    b.Navigation("ServiceReportParts");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.ServiceReport", b =>
                {
                    b.Navigation("ServiceReportParts");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.ServiceTicket", b =>
                {
                    b.Navigation("ServiceReports");
                });

            modelBuilder.Entity("RangeTech.ServiceApp.Api.Domain.Entities.TaskType", b =>
                {
                    b.Navigation("WorkTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
